apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: business-cadence
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: registry.jetbrains.team/p/CADENCE/containers/business-cadence
      docker: {}
  local:
    useDockerCLI: false
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: business-cadence
        remoteChart: oci://registry.jetbrains.team/p/cb/helm-charts/simple-app # You can leave it or specify any your helm chart or from your repo
        version: 0.2.1
        upgradeOnChange: true
        setValueTemplates:
          image: "{{.IMAGE_FULLY_QUALIFIED}}" # Must match you container image path from Space
          imagePullSecret: "{{.IMAGE_PULL_SECRET}}"
          applicationName: "{{.APPLICATION_NAME}}"
        valuesFiles:
          - values.yaml