import { ICalendarList } from "./services/redux/calendars/calendars.types.ts";

export const testCalendarData: ICalendarList = {
  calendars: [
    // {
    //   id: "1",
    //   accessRole: "reader",
    //   backgroundColor: "",
    //   colorId: "",
    //   conferenceProperties: {
    //     allowedConferenceSolutionTypes: [],
    //   },
    //   defaultReminders: [],
    //   description: "",
    //   etag: "",
    //   foregroundColor: "",
    //   kind: "calendar#calendar",
    //   selected: false,
    //   summary: "All events",
    //   timeZone: "",
    //   events: [],
    // },
    {
      id: "2",
      accessRole: "reader",
      backgroundColor: "#DB3D49",
      colorId: "",
      conferenceProperties: {
        allowedConferenceSolutionTypes: [],
      },
      defaultReminders: [],
      description: "",
      etag: "",
      foregroundColor: "",
      kind: "calendar#calendar",
      selected: true,
      summary: "YouTrack Team",
      events: [
        {
          id: "2-0",
          summary: "Gathering",
          backgroundColor: "#DB3D49",
          calendarId: "2",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-01-01T15:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-01-01T17:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "2-0",
          summary: "Release",
          backgroundColor: "#DB3D49",
          calendarId: "2",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-01-01T09:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-01-01T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "2-1",
          summary: "Gathering",
          backgroundColor: "#DB3D49",
          calendarId: "2",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-01-15T15:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-01-20T17:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "2-2",
          summary: "Apps Release",
          backgroundColor: "#DB3D49",
          calendarId: "2",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-03-18T15:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-04-07T17:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "2-3",
          summary: "Gathering",
          backgroundColor: "#DB3D49",
          calendarId: "2",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-06-18T15:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-06-24T17:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "2-4",
          summary: "Apps Release",
          backgroundColor: "#DB3D49",
          calendarId: "2",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-07-22T15:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-08-04T17:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
      ],
    },
    {
      id: "3",
      accessRole: "reader",
      backgroundColor: "#BF890C",
      colorId: "",
      conferenceProperties: {
        allowedConferenceSolutionTypes: [],
      },
      defaultReminders: [],
      description: "",
      etag: "",
      foregroundColor: "",
      kind: "calendar#calendar",
      selected: true,
      summary: "Personal",
      timeZone: "",
      events: [
        {
          id: "3-1",
          summary: "Monthly Report",
          backgroundColor: "#BF890C",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-01-22T15:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-02-04T17:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "3-2",
          summary: "Job interviews",
          backgroundColor: "#BF890C",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-03-04T15:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-03-10T17:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "3-3",
          summary: "Workshop for Inn...",
          backgroundColor: "#BF890C",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-04-08T15:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-04-14T17:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "3-4",
          summary: "Monthly Report",
          backgroundColor: "#BF890C",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-04-22T15:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-04-28T17:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "3-8",
          summary: "Service quality analysis",
          backgroundColor: "#BF890C",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-06-11T15:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-06-17T17:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        // {
        //   id: "3-9",
        //   summary: "Monthly Report",
        //   backgroundColor: "#BF890C",
        //   calendarId: "3",
        //   created: "",
        //   creator: { email: "", displayName: "", self: false },
        //   description: "",
        //   end: { date: "" },
        //   etag: "",
        //   eventType: "",
        //   htmlLink: "",
        //   iCalUID: "",
        //   kind: "",
        //   organizer: { email: "", displayName: "", self: false },
        //   sequence: 0,
        //   status: "",
        //   transparency: "",
        //   updated: "",
        //   visibility: "",
        // },
        // { id: "3-10", summary: "Monthly Report", calendarId: "3", created: "", creator: { email: "", displayName: "", self: false }, description: "", end: { date: "" }, etag: "", eventType: "", htmlLink: "", iCalUID: "", kind: "", organizer: { email: "", displayName: "", self: false }, sequence: 0, start: { date: "" }, status: "", transparency: "", updated: "", visibility: "" },
        // { id: "3-11", summary: "Monthly Report", calendarId: "3", created: "", creator: { email: "", displayName: "", self: false }, description: "", end: { date: "" }, etag: "", eventType: "", htmlLink: "", iCalUID: "", kind: "", organizer: { email: "", displayName: "", self: false }, sequence: 0, start: { date: "" }, status: "", transparency: "", updated: "", visibility: "" },
        // { id: "3-12", summary: "Monthly Report", calendarId: "3", created: "", creator: { email: "", displayName: "", self: false }, description: "", end: { date: "" }, etag: "", eventType: "", htmlLink: "", iCalUID: "", kind: "", organizer: { email: "", displayName: "", self: false }, sequence: 0, start: { date: "" }, status: "", transparency: "", updated: "", visibility: "" },
        // { id: "3-13", summary: "Monthly Report", calendarId: "3", created: "", creator: { email: "", displayName: "", self: false }, description: "", end: { date: "" }, etag: "", eventType: "", htmlLink: "", iCalUID: "", kind: "", organizer: { email: "", displayName: "", self: false }, sequence: 0, start: { date: "" }, status: "", transparency: "", updated: "", visibility: "" },
      ],
    },
    {
      id: "4",
      accessRole: "reader",
      backgroundColor: "#6BBCFF",
      colorId: "",
      conferenceProperties: {
        allowedConferenceSolutionTypes: [],
      },
      defaultReminders: [],
      description: "",
      etag: "",
      foregroundColor: "",
      kind: "calendar#calendar",
      selected: true,
      summary: "JetBrains IDEs Release",
      timeZone: "",
      events: [
        {
          id: "1-9",
          summary: "Meeting",
          backgroundColor: "#6BBCFF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-01-02T09:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-01-02T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "1-9",
          summary: "Team Strategy Meeting",
          backgroundColor: "#6BBCFF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-03-10T09:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-03-31T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "2-7",
          summary: "Quarterly Financial Review",
          backgroundColor: "#6BBCFF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-04-21T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-04-28T14:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "3-6",
          summary: "Product Launch Preparation",
          backgroundColor: "#6BBCFF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-07-01T08:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-08-04T18:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "4-5",
          summary: "Client Workshop",
          backgroundColor: "#6BBCFF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-09-05T13:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-09-15T15:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "5-4",
          summary: "Year-end Review",
          backgroundColor: "#6BBCFF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-12-02T09:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-12-22T12:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
      ],
    },
    {
      id: "5",
      accessRole: "reader",
      backgroundColor: "#8650FF",
      colorId: "",
      conferenceProperties: {
        allowedConferenceSolutionTypes: [],
      },
      defaultReminders: [],
      description: "",
      etag: "",
      foregroundColor: "",
      kind: "calendar#calendar",
      selected: true,
      summary: "Public Holidays",
      timeZone: "",
      events: [
        {
          id: "12-1",
          summary: "New Year Celebr...",
          backgroundColor: "#8650FF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-01-01T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-01-01T22:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "13-2",
          summary: "Winter Break",
          backgroundColor: "#8650FF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-02-12T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-02-18T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "14-3",
          summary: "International Wo...",
          backgroundColor: "#8650FF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-03-08T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-03-09T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "15-4",
          summary: "Easter Break",
          backgroundColor: "#8650FF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-04-01T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-04-07T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "16-5",
          summary: "Labor Day",
          backgroundColor: "#8650FF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-05-01T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-05-02T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "17-6",
          summary: "Midsummer Festi...",
          backgroundColor: "#8650FF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-06-21T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-06-22T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "18-7",
          summary: "Independence Day",
          backgroundColor: "#8650FF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-07-04T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-07-05T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "19-8",
          summary: "Summer Break",
          backgroundColor: "#8650FF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-08-01T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-08-15T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "21-10",
          summary: "Autumn Break",
          backgroundColor: "#8650FF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-10-10T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-10-15T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "22-11",
          summary: "Halloween",
          backgroundColor: "#8650FF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-10-31T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-11-01T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "23-12",
          summary: "Black Friday",
          backgroundColor: "#8650FF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-11-29T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-11-30T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "24-13",
          summary: "New Year's Eve",
          backgroundColor: "#8650FF",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-12-31T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-12-31T22:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
      ],
    },
    {
      id: "6",
      accessRole: "reader",
      backgroundColor: "#79AF3B",
      colorId: "",
      conferenceProperties: {
        allowedConferenceSolutionTypes: [],
      },
      defaultReminders: [],
      description: "",
      etag: "",
      foregroundColor: "",
      kind: "calendar#calendar",
      selected: true,
      summary: "JetBrains Team Events",
      timeZone: "",
      events: [
        {
          id: "29-18",
          summary: "Iceland",
          backgroundColor: "#79AF3B",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-01-05T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-01-12T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "30-19",
          summary: "USA",
          backgroundColor: "#79AF3B",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-02-01T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-02-07T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "25-14",
          summary: "Summer Getaway",
          backgroundColor: "#79AF3B",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-07-05T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-07-12T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "26-15",
          summary: "Germany",
          backgroundColor: "#79AF3B",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-08-10T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-08-17T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "27-16",
          summary: "Autumn Retreat",
          backgroundColor: "#79AF3B",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-09-20T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-09-30T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "28-17",
          summary: "Ski Trip",
          backgroundColor: "#79AF3B",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-12-10T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-12-17T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
      ],
    },
    {
      id: "7",
      accessRole: "reader",
      backgroundColor: "#EBB100",
      colorId: "",
      conferenceProperties: {
        allowedConferenceSolutionTypes: [],
      },
      defaultReminders: [],
      description: "",
      etag: "",
      foregroundColor: "",
      kind: "calendar#calendar",
      selected: false,
      summary: "Family",
      timeZone: "",
      events: [
        {
          id: "31-20",
          summary: "Family Reunion",
          backgroundColor: "#EBB100",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-03-15T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-03-17T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "32-21",
          summary: "Weekend Getaway",
          backgroundColor: "#EBB100",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-05-10T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-05-12T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "33-22",
          summary: "Summer Picnic",
          backgroundColor: "#EBB100",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-06-22T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-06-23T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "34-23",
          summary: "Cousin's Birthday Party",
          backgroundColor: "#EBB100",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-08-05T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-08-05T23:59:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "35-24",
          summary: "Holiday Gathering",
          backgroundColor: "#EBB100",
          calendarId: "3",
          created: "",
          creator: { email: "", displayName: "", self: false },
          description: "",
          start: {
            dateTime: "2024-12-24T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-12-26T00:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: { email: "", displayName: "", self: false },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
      ],
    },
    {
      id: "8",
      accessRole: "reader",
      backgroundColor: "#28B8A0",
      colorId: "",
      conferenceProperties: {
        allowedConferenceSolutionTypes: [],
      },
      defaultReminders: [],
      description: "",
      etag: "",
      foregroundColor: "",
      kind: "calendar#calendar",
      selected: false,
      summary: "Preply",
      timeZone: "",
      events: [
        {
          id: "lesson-1",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-01-01T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-01-01T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-2",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-01-15T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-01-15T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-3",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-01-29T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-01-29T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-4",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-02-12T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-02-12T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-5",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-02-26T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-02-26T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-6",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-03-11T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-03-11T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-7",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-03-25T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-03-25T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-8",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-04-08T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-04-08T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-9",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-04-22T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-04-22T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-10",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-05-06T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-05-06T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-11",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-05-20T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-05-20T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-12",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-06-03T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-06-03T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-13",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-06-17T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-06-17T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-14",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-07-01T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-07-01T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-15",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-07-15T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-07-15T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-16",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-07-29T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-07-29T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-17",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-08-12T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-08-12T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-18",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-08-26T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-08-26T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-19",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-09-09T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-09-09T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-20",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-09-23T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-09-23T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-21",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-10-07T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-10-07T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-22",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-10-21T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-10-21T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-23",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-11-04T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-11-04T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-24",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-11-18T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-11-18T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-25",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-12-02T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-12-02T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
        {
          id: "lesson-26",
          summary: "Lesson",
          backgroundColor: "#28B8A0",
          calendarId: "3",
          created: "",
          creator: {
            email: "",
            displayName: "",
            self: false,
          },
          description: "",
          start: {
            dateTime: "2024-12-16T10:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          end: {
            dateTime: "2024-12-16T11:00:00+00:00",
            timeZone: "Asia/Nicosia",
          },
          etag: "",
          eventType: "",
          htmlLink: "",
          iCalUID: "",
          kind: "",
          organizer: {
            email: "",
            displayName: "",
            self: false,
          },
          sequence: 0,
          status: "",
          transparency: "",
          updated: "",
          visibility: "",
        },
      ],
    },
  ],
};
